import React from 'react'

export const Pabahay = [
    {
      id: 1,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "John Doe",
      email: "user@gmail.com",
      age: 30,
      address: "123 Main St",
      gender: "Male",
      status: "Activated",
      created: "2024-01-01T12:00:00.000Z"
    },
    {
      id: 2,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Jane Smith",
      email: "user@gmail.com",
      age: 25,
      address: "456 Elm St",
      gender: "Female",
      city: "Sometown",
      status: "Not Activated",
      created: "2024-02-02T12:00:00.000Z"
    },
    {
      id: 3,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Alice Johnson",
      email: "user@gmail.com",
      age: 40,
      address: "789 Oak St",
      gender: "Female",
      status: "Not Activated",
      created: "2024-03-03T12:00:00.000Z"
    },
    {
      id: 4,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Juan Dela Cruz",
      email: "user@gmail.com",
      age: 26,
      address: "123 Main St",
      gender: "Male",
      status: "Activated",
      created: "2024-04-04T12:00:00.000Z"
    },
    {
      id: 5,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "John Doe",
      email: "user@gmail.com",
      age: 19,
      address: "123 Main St",
      gender: "Male",
      status: "Activated",
      created: "2024-05-05T12:00:00.000Z"
    },
  ];
export const Carissa = [
    {
      id: 1,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "John Doe",
      email: "user@gmail.com",
      age: 30,
      address: "123 Main St",
      gender: "Male",
      status: "Activated",
    },
    {
      id: 2,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Jane Smith",
      email: "user@gmail.com",
      age: 25,
      address: "456 Elm St",
      gender: "Female",
      city: "Sometown",
      status: "Not Activated",
    },
    {
      id: 3,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Alice Johnson",
      email: "user@gmail.com",
      age: 40,
      address: "789 Oak St",
      gender: "Female",
      status: "Not Activated",
    },
    {
      id: 1,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "John Doe",
      email: "user@gmail.com",
      age: 30,
      address: "123 Main St",
      gender: "Male",
      status: "Activated",
    },
  ];
export const Lumina = [
    {
      id: 1,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "John Doe",
      email: "user@gmail.com",
      age: 30,
      address: "123 Main St",
      gender: "Male",
      status: "Activated",
    },
    {
      id: 2,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Jane Smith",
      email: "user@gmail.com",
      age: 25,
      address: "456 Elm St",
      gender: "Female",
      city: "Sometown",
      status: "Not Activated",
    },
  ];