import React from 'react'
// scroll down to see the data of lumina and carissa
export const Pabahay = [
    {
      id: 1,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "John Does",
      email: "user@gmail.com",
      age: 30,
      address: "123 Main St",
      gender: "Male",
      status: "Verified",
      created: "2024-07-01"
    },
    {
      id: 2,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Jane Smith",
      email: "user@gmail.com",
      age: 25,
      address: "456 Elm St",
      gender: "Female",
      city: "Sometown",
      status: "Not Verified",
      created: "2024-03-03"
    },
    {
      id: 3,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Alice Johnson",
      email: "user@gmail.com",
      age: 40,
      address: "789 Oak St",
      gender: "Female",
      status: "Not Verified",
      created: "2024-05-03"
    },
    {
      id: 4,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Juan Dela Cruz",
      email: "user@gmail.com",
      age: 26,
      address: "123 Main St",
      gender: "Male",
      status: "Verified",
      created: "2024-04-04T12:00:00.000Z"
    },
    {
      id: 5,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "John Doe",
      email: "user@gmail.com",
      age: 19,
      address: "123 Main St",
      gender: "Male",
      status: "Verified",
      created: "2024-11-05T12:00:00.000Z"
    },
    {
      id: 6,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "Emily Johnson",
      email: "emily@example.com",
      age: 35,
      address: "789 Pine St",
      gender: "Female",
      status: "Not Verified",
      created: "2024-06-06T12:00:00.000Z"
    },
    {
      id: 7,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Michael Brown",
      email: "michael@example.com",
      age: 45,
      address: "456 Maple St",
      gender: "Male",
      status: "Verified",
      created: "2024-07-07T12:00:00.000Z"
    },
    {
      id: 8,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "Sophia Rodriguez",
      email: "sophia@example.com",
      age: 28,
      address: "789 Oak St",
      gender: "Female",
      status: "Not Verified",
      created: "2024-08-08T12:00:00.000Z"
    },
    {
      id: 9,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Olivia Martinez",
      email: "olivia@example.com",
      age: 29,
      address: "234 Oak St",
      gender: "Female",
      status: "Not Verified",
      created: "2024-10-10T12:00:00.000Z"
    },
    {
      id: 10,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "William Taylor",
      email: "william@example.com",
      age: 38,
      address: "567 Elm St",
      gender: "Male",
      status: "Verified",
      created: "2024-11-11T12:00:00.000Z"
    },
    {
      id: 11,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "Isabella Anderson",
      email: "isabella@example.com",
      age: 24,
      address: "890 Maple St",
      gender: "Female",
      status: "Verified",
      created: "2024-12-12T12:00:00.000Z"
    },
    {
      id: 12,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Ethan Harris",
      email: "ethan@example.com",
      age: 31,
      address: "123 Pine St",
      gender: "Male",
      status: "Not Verified",
      created: "2025-01-01T12:00:00.000Z"
    },
    {
      id: 13,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Charlotte Jackson",
      email: "charlotte@example.com",
      age: 27,
      address: "456 Cedar St",
      gender: "Female",
      status: "Verified",
      created: "2025-02-02T12:00:00.000Z"
    },
    {
      id: 14,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Mason Moore",
      email: "mason@example.com",
      age: 36,
      address: "789 Elm St",
      gender: "Male",
      status: "Verified",
      created: "2025-03-03T12:00:00.000Z"
    },
    {
      id: 15,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "Ava Clark",
      email: "ava@example.com",
      age: 22,
      address: "123 Oak St",
      gender: "Female",
      status: "Not Verified",
      created: "2025-04-04T12:00:00.000Z"
    },
    {
      id: 16,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Liam Rodriguez",
      email: "liam@example.com",
      age: 34,
      address: "456 Maple St",
      gender: "Male",
      status: "Verified",
      created: "2025-05-05T12:00:00.000Z"
    },
    {
      id: 17,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Harper Thompson",
      email: "harper@example.com",
      age: 26,
      address: "789 Cedar St",
      gender: "Female",
      status: "Not Verified",
      created: "2025-06-06T12:00:00.000Z"
    },
    {
      id: 18,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "Noah Wilson",
      email: "noah@example.com",
      age: 30,
      address: "123 Elm St",
      gender: "Male",
      status: "Verified",
      created: "2025-07-07T12:00:00.000Z"
    },
    {
      id: 19,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "Amelia White",
      email: "amelia@example.com",
      age: 29,
      address: "456 Pine St",
      gender: "Female",
      status: "Verified",
      created: "2025-08-08T12:00:00.000Z"
    },
    {
      id: 20,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Logan Martinez",
      email: "logan@example.com",
      age: 32,
      address: "789 Maple St",
      gender: "Male",
      status: "Not Verified",
      created: "2025-09-09T12:00:00.000Z"
    },
    {
      id: 21,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Ella Lee",
      email: "ella@example.com",
      age: 25,
      address: "123 Cedar St",
      gender: "Female",
      status: "Verified",
      created: "2025-10-10T12:00:00.000Z"
    },
    {
      id: 22,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Sebastian Anderson",
      email: "sebastian@example.com",
      age: 37,
      address: "456 Oak St",
      gender: "Male",
      status: "Not Verified",
      created: "2025-11-11T12:00:00.000Z"
    },
    {
      id: 23,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "Mia Harris",
      email: "mia@example.com",
      age: 28,
      address: "789 Pine St",
      gender: "Female",
      status: "Verified",
      created: "2025-12-12T12:00:00.000Z"
    },
    {
      id: 24,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Elijah Brown",
      email: "elijah@example.com",
      age: 33,
      address: "123 Maple St",
      gender: "Male",
      status: "Verified",
      created: "2026-01-01T12:00:00.000Z"
    },
    {
      id: 25,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "Avery Taylor",
      email: "avery@example.com",
      age: 30,
      address: "456 Cedar St",
      gender: "Female",
      status: "Not Verified",
      created: "2026-02-02T12:00:00.000Z"
    },
    {
      id: 26,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "Liam Smith",
      email: "liam@example.com",
      age: 28,
      address: "123 Pine St",
      gender: "Male",
      status: "Verified",
      created: "2026-03-03T12:00:00.000Z"
    },
    {
      id: 27,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Sophia Johnson",
      email: "sophia@example.com",
      age: 25,
      address: "456 Cedar St",
      gender: "Female",
      status: "Not Verified",
      created: "2026-04-04T12:00:00.000Z"
    },
    {
      id: 28,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Jackson Brown",
      email: "jackson@example.com",
      age: 34,
      address: "789 Elm St",
      gender: "Male",
      status: "Verified",
      created: "2026-05-05T12:00:00.000Z"
    },
    {
      id: 29,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Olivia Wilson",
      email: "olivia@example.com",
      age: 31,
      address: "123 Oak St",
      gender: "Female",
      status: "Not Verified",
      created: "2026-06-06T12:00:00.000Z"
    },
    {
      id: 30,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "Noah Taylor",
      email: "noah@example.com",
      age: 29,
      address: "456 Maple St",
      gender: "Male",
      status: "Verified",
      created: "2026-07-07T12:00:00.000Z"
    },
    {
      id: 31,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "Emma Garcia",
      email: "emma@example.com",
      age: 27,
      address: "789 Pine St",
      gender: "Female",
      status: "Not Verified",
      created: "2026-08-08T12:00:00.000Z"
    },
    {
      id: 32,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Michael Martinez",
      email: "michael@example.com",
      age: 33,
      address: "123 Cedar St",
      gender: "Male",
      status: "Verified",
      created: "2026-09-09T12:00:00.000Z"
    },
    {
      id: 33,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Ava Rodriguez",
      email: "ava@example.com",
      age: 30,
      address: "456 Oak St",
      gender: "Female",
      status: "Verified",
      created: "2026-10-10T12:00:00.000Z"
    },
    {
      id: 34,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "William Lopez",
      email: "william@example.com",
      age: 32,
      address: "789 Maple St",
      gender: "Male",
      status: "Not Verified",
      created: "2026-11-11T12:00:00.000Z"
    },
    {
      id: 35,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "Harper Clark",
      email: "harper@example.com",
      age: 28,
      address: "123 Pine St",
      gender: "Female",
      status: "Verified",
      created: "2026-12-12T12:00:00.000Z"
    },
    {
      id: 36,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "Evelyn Lee",
      email: "evelyn@example.com",
      age: 29,
      address: "456 Cedar St",
      gender: "Female",
      status: "Not Verified",
      created: "2027-01-01T12:00:00.000Z"
    },
    {
      id: 37,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Alexander Harris",
      email: "alexander@example.com",
      age: 34,
      address: "789 Elm St",
      gender: "Male",
      status: "Verified",
      created: "2027-02-02T12:00:00.000Z"
    },
    {
      id: 38,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Madison King",
      email: "madison@example.com",
      age: 31,
      address: "123 Oak St",
      gender: "Female",
      status: "Verified",
      created: "2027-03-03T12:00:00.000Z"
    },
    {
      id: 39,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Daniel Thompson",
      email: "daniel@example.com",
      age: 33,
      address: "456 Maple St",
      gender: "Male",
      status: "Not Verified",
      created: "2027-04-04T12:00:00.000Z"
    },
    {
      id: 40,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "Addison Wright",
      email: "addison@example.com",
      age: 30,
      address: "789 Pine St",
      gender: "Female",
      status: "Verified",
      created: "2027-05-05T12:00:00.000Z"
    },
    {
      id: 41,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "Sebastian Scott",
      email: "sebastian@example.com",
      age: 32,
      address: "123 Cedar St",
      gender: "Male",
      status: "Not Verified",
      created: "2027-06-06T12:00:00.000Z"
    },
    {
      id: 42,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Penelope Turner",
      email: "penelope@example.com",
      age: 28,
      address: "456 Oak St",
      gender: "Female",
      status: "Verified",
      created: "2027-07-07T12:00:00.000Z"
    },
    {
      id: 43,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Jack Miller",
      email: "jack@example.com",
      age: 35,
      address: "789 Maple St",
      gender: "Male",
      status: "Verified",
      created: "2027-08-08T12:00:00.000Z"
    },
    {
      id: 44,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Aria Hill",
      email: "aria@example.com",
      age: 27,
      address: "123 Pine St",
      gender: "Female",
      status: "Not Verified",
      created: "2027-09-09T12:00:00.000Z"
    },
    {
      id: 45,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "Henry Adams",
      email: "henry@example.com",
      age: 33,
      address: "456 Cedar St",
      gender: "Male",
      status: "Verified",
      created: "2027-10-10T12:00:00.000Z"
    },
    {
      id: 46,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "Mia Baker",
      email: "mia@example.com",
      age: 30,
      address: "789 Elm St",
      gender: "Female",
      status: "Verified",
      created: "2027-11-11T12:00:00.000Z"
    },
    {
      id: 47,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Ethan Walker",
      email: "ethan@example.com",
      age: 32,
      address: "123 Oak St",
      gender: "Male",
      status: "Not Verified",
      created: "2027-12-12T12:00:00.000Z"
    },
    {
      id: 48,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Ella Garcia",
      email: "ella@example.com",
      age: 28,
      address: "456 Maple St",
      gender: "Female",
      status: "Verified",
      created: "2028-01-01T12:00:00.000Z"
    },
    {
      id: 49,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Logan Perez",
      email: "logan@example.com",
      age: 35,
      address: "789 Pine St",
      gender: "Male",
      status: "Not Verified",
      created: "2028-02-02T12:00:00.000Z"
    },
    {
      id: 50,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "Avery Scott",
      email: "avery@example.com",
      age: 27,
      address: "123 Cedar St",
      gender: "Female",
      status: "Verified",
      created: "2028-03-03T12:00:00.000Z"
    },
    {
      id: 51,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "Lucas Morgan",
      email: "lucas@example.com",
      age: 31,
      address: "456 Oak St",
      gender: "Male",
      status: "Not Verified",
      created: "2028-04-04T12:00:00.000Z"
    },
    {
      id: 52,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Scarlett Gonzalez",
      email: "scarlett@example.com",
      age: 29,
      address: "789 Maple St",
      gender: "Female",
      status: "Verified",
      created: "2028-05-05T12:00:00.000Z"
    },
    {
      id: 53,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Wyatt Martinez",
      email: "wyatt@example.com",
      age: 33,
      address: "123 Pine St",
      gender: "Male",
      status: "Verified",
      created: "2028-06-06T12:00:00.000Z"
    },
    {
      id: 54,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Layla Turner",
      email: "layla@example.com",
      age: 28,
      address: "456 Cedar St",
      gender: "Female",
      status: "Not Verified",
      created: "2028-07-07T12:00:00.000Z"
    },
    {
      id: 55,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "Oliver Hill",
      email: "oliver@example.com",
      age: 30,
      address: "789 Oak St",
      gender: "Male",
      status: "Verified",
      created: "2028-08-08T12:00:00.000Z"
    },
    {
      id: 56,
      img: "https://flowbite.com/docs/images/people/profile-picture-1.jpg",
      name: "Chloe Adams",
      email: "chloe@example.com",
      age: 32,
      address: "123 Maple St",
      gender: "Female",
      status: "Verified",
      created: "2028-09-09T12:00:00.000Z"
    },
    {
      id: 57,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "Levi Baker",
      email: "levi@example.com",
      age: 27,
      address: "456 Pine St",
      gender: "Male",
      status: "Not Verified",
      created: "2028-10-10T12:00:00.000Z"
    },
    {
      id: 58,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Zoe Hill",
      email: "zoe@example.com",
      age: 29,
      address: "789 Cedar St",
      gender: "Female",
      status: "Verified",
      created: "2028-11-11T12:00:00.000Z"
    },
    {
      id: 59,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Mason Wilson",
      email: "mason@example.com",
      age: 34,
      address: "123 Oak St",
      gender: "Male",
      status: "Verified",
      created: "2028-12-12T12:00:00.000Z"
    },
    {
      id: 60,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "Mila Lee",
      email: "mila@example.com",
      age: 31,
      address: "456 Maple St",
      gender: "Female",
      status: "Not Verified",
      created: "2029-01-01T12:00:00.000Z"
    },
  ];
export const Carissa = [
    {
      id: 1,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "John Doe",
      email: "user@gmail.com",
      age: 30,
      address: "123 Main St",
      gender: "Male",
      status: "Verified",
    },
    {
      id: 2,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Jane Smith",
      email: "user@gmail.com",
      age: 25,
      address: "456 Elm St",
      gender: "Female",
      city: "Sometown",
      status: "Not Verified",
    },
    {
      id: 3,
      img: "https://flowbite.com/docs/images/people/profile-picture-3.jpg",
      name: "Alice Johnson",
      email: "user@gmail.com",
      age: 40,
      address: "789 Oak St",
      gender: "Female",
      status: "Not Verified",
    },
    {
      id: 1,
      img: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
      name: "John Doe",
      email: "user@gmail.com",
      age: 30,
      address: "123 Main St",
      gender: "Male",
      status: "Verified",
    },
  ];
export const Lumina = [
    {
      id: 1,
      img: "https://flowbite.com/docs/images/people/profile-picture-5.jpg",
      name: "John Doe",
      email: "user@gmail.com",
      age: 30,
      address: "123 Main St",
      gender: "Male",
      status: "Verified",
    },
    {
      id: 2,
      img: "https://flowbite.com/docs/images/people/profile-picture-4.jpg",
      name: "Jane Smith",
      email: "user@gmail.com",
      age: 25,
      address: "456 Elm St",
      gender: "Female",
      city: "Sometown",
      status: "Not Verified",
    },
  ];